language: ruby
rvm:
- 2.6.3
dist: bionic

before_install:
    - gem install bundler # travis comes with bundler 1; we want bundler 2.
before_script:
 - chmod +x ./scripts/travis # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: "./scripts/travis"

# branch whitelist, only for GitHub Pages
branches:
  only:
  - development

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  local_dir: _site/  # deploy this directory containing final build
  github_token: $GITHUB_API_KEY # Set in travis-ci.org dashboard
  target_branch: master
  on:
    branch: development 
